#!/usr/bin/python
# -*- coding: utf-8 -*-

import os, sys, wx
try:
    import wx
    print "* wxWidgets module loaded"
except:
    print "! wxWidgets module not installed. Exiting..."
    exit(101)

from lib import gui

def main():
    app = wx.App(False)
    frame = gui.MainWindow(None)
    app.MainLoop()
    
if __name__ == "__main__":
    main()
    exit(0)
